### ISSUE TITLE
Deleting files during merge commit breaks voom freshen

### ISSUE THREAD

**Issue by dzaharee** [LonoCloud/lein-voom#37]
Deleting any file during a merge commit will cause voom freshen to fail with a git error of:
> fatal: Path '_path_' exists on disk, but not in '_sha_'.\n

I've created a minimal case: [dzaharee/voom-breakage-dep](https://github.com/dzaharee/voom-breakage-dep). To break voom, clone [dzaharee/voom-breakage](https://github.com/dzaharee/voom-breakage) and run `lein voom freshen`.

**Comment by MichaelDrogalis** [comment]
Closing, fixed in 763d315828999bdf7d14ebf625c4979085fa03e3.
