### ISSUE TITLE
README doesn't contain any examples of a 'voom-version'

### ISSUE THREAD

**Issue by cprice404** [LonoCloud/lein-voom#40]
The README mentions in a few places that voom will do special things for dependencies that have a `voom-version`, and that's what I remember from the clojure/conj talk last year, but there are no examples of how to specify a `voom-version` in your `project.clj` file in the current contents of the README, nor anywhere else in the project that I've found so far :)  I'm probably missing something obvious...

**Comment by moquist** [comment]
Should've looked at the issues list back in December. At least I'm connecting these dots now: https://github.com/LonoCloud/lein-voom/pull/42

**Comment by abrooks** [comment]
Addressed by PR #42.
