### ISSUE TITLE
project.clj errors can prevent depending on other projects in the same git repo

### ISSUE THREAD

**Issue by Chouser** [LonoCloud/lein-voom#63]
Let project A depend on a voom-version of project B.
Let project B at that version live in a git repo that also has a project X.
Let project X have a bug in its project.clj that causes an error when project.clj is read.

Now running "voom build deps" in project A may cause voom to crash before finding or building project B, because in looking for B it tried to load X.

The logged output only mentions project B; the real culprit, project X, is never mentioned.
Even if project X is fixed, pushing a new version of it will not help without changes to A or B, since the fix will be in a different version of the repo than A is depending on.

One workaround is to run "lein voom install" in the version of project B that project A depends on.

**Comment by abrooks** [comment]
It's worth noting that this arose with lein 2.8.1 which started throwing exceptions for repositories that do not use TLS (cf. [lein FAQ](https://github.com/technomancy/leiningen/blob/master/doc/FAQ.md) question about `Tried to use insecure HTTP repository without TLS`).

We generally were not robustly handling project reads so any leiningen issue throwing an exception during project read would cause this problem.
